if(DEFINED CLI_PATH)
    set(CLI "${CLI_PATH}")
else()
    if(NOT DEFINED BUILD_DIR)
        message(FATAL_ERROR "BUILD_DIR or CLI_PATH is required")
    endif()

    if(WIN32)
        set(CLI "${BUILD_DIR}/Release/vektoryum_cli.exe")
    else()
        set(CLI "${BUILD_DIR}/vektoryum_cli")
    endif()
endif()

if(NOT EXISTS "${CLI}")
    message(FATAL_ERROR "CLI executable not found: ${CLI}")
endif()

set(expected_help "usage: vektoryum_cli [--version|--help|--probe-input FILE|--convert INPUT OUTPUT|--certified-export REQUEST_ID [CERTIFICATE_SHA256]|--certified-convert INPUT OUTPUT FORMAT]\n")
execute_process(COMMAND "${CLI}" --help RESULT_VARIABLE help_rc OUTPUT_VARIABLE help_out ERROR_VARIABLE help_err)
if(NOT help_rc EQUAL 0 OR NOT help_out STREQUAL expected_help OR NOT help_err STREQUAL "")
    message(FATAL_ERROR "--help contract mismatch: rc=${help_rc} stdout=[${help_out}] stderr=[${help_err}]")
endif()

execute_process(COMMAND "${CLI}" --version RESULT_VARIABLE version_rc_a OUTPUT_VARIABLE version_out_a ERROR_VARIABLE version_err_a)
execute_process(COMMAND "${CLI}" --version RESULT_VARIABLE version_rc_b OUTPUT_VARIABLE version_out_b ERROR_VARIABLE version_err_b)
if(NOT version_rc_a EQUAL 0 OR NOT version_rc_b EQUAL 0 OR NOT version_err_a STREQUAL "" OR NOT version_err_b STREQUAL "")
    message(FATAL_ERROR "--version must succeed on stdout only")
endif()
if(NOT version_out_a STREQUAL version_out_b)
    message(FATAL_ERROR "--version is not byte-for-byte repeatable")
endif()
if(NOT version_out_a MATCHES "^Vektoryum v2 core [0-9]+\\.[0-9]+\\.[0-9]+\n$")
    message(FATAL_ERROR "--version stdout shape mismatch: [${version_out_a}]")
endif()

execute_process(COMMAND "${CLI}" RESULT_VARIABLE default_rc OUTPUT_VARIABLE default_out ERROR_VARIABLE default_err)
if(NOT default_rc EQUAL 0 OR NOT default_out STREQUAL version_out_a OR NOT default_err STREQUAL "")
    message(FATAL_ERROR "no-argument compatibility contract mismatch")
endif()

set(expected_error "error: unsupported command line\n")
foreach(case_name IN ITEMS unknown near_help empty_arg multi_arg)
    if(case_name STREQUAL "unknown")
        execute_process(COMMAND "${CLI}" --unknown RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    elseif(case_name STREQUAL "near_help")
        execute_process(COMMAND "${CLI}" --help=1 RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    elseif(case_name STREQUAL "empty_arg")
        execute_process(COMMAND "${CLI}" "" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    else()
        execute_process(COMMAND "${CLI}" --version --help RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    endif()
    if(NOT rc EQUAL 64 OR NOT out STREQUAL "" OR NOT err STREQUAL expected_error)
        message(FATAL_ERROR "${case_name} must fail closed with rc=64, empty stdout and canonical stderr; rc=${rc} stdout=[${out}] stderr=[${err}]")
    endif()
endforeach()

execute_process(COMMAND "${CLI}" --unknown RESULT_VARIABLE repeat_rc OUTPUT_VARIABLE repeat_out ERROR_VARIABLE repeat_err)
if(NOT repeat_rc EQUAL 64 OR NOT repeat_out STREQUAL "" OR NOT repeat_err STREQUAL expected_error)
    message(FATAL_ERROR "unsupported-command stderr fixture is not repeatable")
endif()

execute_process(COMMAND "${CLI}" --convert "${CMAKE_CURRENT_LIST_DIR}/definitely-missing-input.png" "${CMAKE_CURRENT_BINARY_DIR}/missing-output.pam" RESULT_VARIABLE convert_missing_rc OUTPUT_VARIABLE convert_missing_out ERROR_VARIABLE convert_missing_err)
set(expected_convert_missing "schema_version=vektoryum.raster-convert.v1\nstatus=error\nerror=open_failed\n")
if(NOT convert_missing_rc EQUAL 65 OR NOT convert_missing_out STREQUAL expected_convert_missing OR NOT convert_missing_err STREQUAL "")
    message(FATAL_ERROR "--convert missing-input contract mismatch: rc=${convert_missing_rc} stdout=[${convert_missing_out}] stderr=[${convert_missing_err}]")
endif()

execute_process(COMMAND "${CLI}" --certified-export request-cli-0001 RESULT_VARIABLE certified_rc_a OUTPUT_VARIABLE certified_out_a ERROR_VARIABLE certified_err_a)
execute_process(COMMAND "${CLI}" --certified-export request-cli-0001 RESULT_VARIABLE certified_rc_b OUTPUT_VARIABLE certified_out_b ERROR_VARIABLE certified_err_b)
if(NOT certified_rc_a EQUAL 0 OR NOT certified_rc_b EQUAL 0 OR NOT certified_err_a STREQUAL "" OR NOT certified_err_b STREQUAL "")
    message(FATAL_ERROR "certified export must succeed on canonical stdout only")
endif()
if(NOT certified_out_a STREQUAL certified_out_b)
    message(FATAL_ERROR "certified export is not byte-for-byte repeatable")
endif()
if(NOT certified_out_a MATCHES "^schema_version=vektoryum\\.core-api\\.v1\nrequest_id=request-cli-0001\noperation=certified_export\nstatus=success\nexit_code=0\nerror=none\ncertificate_sha256=[0-9a-f][0-9a-f]+\n$")
    message(FATAL_ERROR "certified export canonical stdout shape mismatch: [${certified_out_a}]")
endif()
string(REGEX MATCH "certificate_sha256=([0-9a-f]+)\n$" digest_line "${certified_out_a}")
set(valid_digest "${CMAKE_MATCH_1}")
string(LENGTH "${valid_digest}" valid_digest_length)
if(NOT valid_digest_length EQUAL 64)
    message(FATAL_ERROR "certified export must preserve one exact 64-hex Stage 11 certificate digest")
endif()
execute_process(COMMAND "${CLI}" --certified-export request-cli-0001 "${valid_digest}" RESULT_VARIABLE explicit_rc OUTPUT_VARIABLE explicit_out ERROR_VARIABLE explicit_err)
if(NOT explicit_rc EQUAL 0 OR NOT explicit_out STREQUAL certified_out_a OR NOT explicit_err STREQUAL "")
    message(FATAL_ERROR "explicit exact Stage 11 certificate identity must produce the same canonical response bytes")
endif()

set(substituted_digest "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
execute_process(COMMAND "${CLI}" --certified-export request-cli-0001 "${substituted_digest}" RESULT_VARIABLE substituted_rc OUTPUT_VARIABLE substituted_out ERROR_VARIABLE substituted_err)
set(expected_substituted "schema_version=vektoryum.core-api.v1\nrequest_id=request-cli-0001\noperation=certified_export\nstatus=error\nexit_code=65\nerror=certificate_provenance_mismatch\ncertificate_sha256=\n")
if(NOT substituted_rc EQUAL 65 OR NOT substituted_out STREQUAL expected_substituted OR NOT substituted_err STREQUAL "")
    message(FATAL_ERROR "certificate substitution must fail closed with canonical Core API response bytes")
endif()
