if(NOT DEFINED BUILD_DIR)
    message(FATAL_ERROR "BUILD_DIR is required")
endif()

if(WIN32)
    set(CLI "${BUILD_DIR}/Release/vektoryum_cli.exe")
else()
    set(CLI "${BUILD_DIR}/vektoryum_cli")
endif()

if(NOT EXISTS "${CLI}")
    message(FATAL_ERROR "CLI executable not found: ${CLI}")
endif()

execute_process(COMMAND "${CLI}" --help RESULT_VARIABLE help_rc OUTPUT_VARIABLE help_out ERROR_VARIABLE help_err)
if(NOT help_rc EQUAL 0 OR NOT help_out STREQUAL "usage: vektoryum_cli [--version|--help]\n" OR NOT help_err STREQUAL "")
    message(FATAL_ERROR "--help contract mismatch: rc=${help_rc} stdout=[${help_out}] stderr=[${help_err}]")
endif()

execute_process(COMMAND "${CLI}" --version RESULT_VARIABLE version_rc_a OUTPUT_VARIABLE version_out_a ERROR_VARIABLE version_err_a)
execute_process(COMMAND "${CLI}" --version RESULT_VARIABLE version_rc_b OUTPUT_VARIABLE version_out_b ERROR_VARIABLE version_err_b)
if(NOT version_rc_a EQUAL 0 OR NOT version_rc_b EQUAL 0 OR NOT version_err_a STREQUAL "" OR NOT version_err_b STREQUAL "")
    message(FATAL_ERROR "--version must succeed on stdout only")
endif()
if(NOT version_out_a STREQUAL version_out_b)
    message(FATAL_ERROR "--version is not byte-for-byte repeatable")
endif()
if(NOT version_out_a MATCHES "^Vektoryum v2 core [0-9]+\\.[0-9]+\\.[0-9]+\n$")
    message(FATAL_ERROR "--version stdout shape mismatch: [${version_out_a}]")
endif()

execute_process(COMMAND "${CLI}" RESULT_VARIABLE default_rc OUTPUT_VARIABLE default_out ERROR_VARIABLE default_err)
if(NOT default_rc EQUAL 0 OR NOT default_out STREQUAL version_out_a OR NOT default_err STREQUAL "")
    message(FATAL_ERROR "no-argument compatibility contract mismatch")
endif()

set(expected_error "error: unsupported command line\n")
foreach(case_name IN ITEMS unknown near_help empty_arg multi_arg)
    if(case_name STREQUAL "unknown")
        execute_process(COMMAND "${CLI}" --unknown RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    elseif(case_name STREQUAL "near_help")
        execute_process(COMMAND "${CLI}" --help=1 RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    elseif(case_name STREQUAL "empty_arg")
        execute_process(COMMAND "${CLI}" "" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    else()
        execute_process(COMMAND "${CLI}" --version --help RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    endif()
    if(NOT rc EQUAL 64 OR NOT out STREQUAL "" OR NOT err STREQUAL expected_error)
        message(FATAL_ERROR "${case_name} must fail closed with rc=64, empty stdout and canonical stderr; rc=${rc} stdout=[${out}] stderr=[${err}]")
    endif()
endforeach()

execute_process(COMMAND "${CLI}" --unknown RESULT_VARIABLE repeat_rc OUTPUT_VARIABLE repeat_out ERROR_VARIABLE repeat_err)
if(NOT repeat_rc EQUAL 64 OR NOT repeat_out STREQUAL "" OR NOT repeat_err STREQUAL expected_error)
    message(FATAL_ERROR "unsupported-command stderr fixture is not repeatable")
endif()
